name: bump_node_app_version

on:
  workflow_call:
    secrets:
      GITHUB_BUILD_TOKEN:
        required: true

jobs:
  bump_node_app_version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_BUILD_TOKEN }}

      - name: Bump Version and Tag
        id: bump
        uses: TriPSs/conventional-changelog-action@v5
        with:
          github-token: ${{ secrets.GITHUB_BUILD_TOKEN }}
          release-count: 10
          skip-on-empty: "true"
          version-file: "app/functions/package.json"
          git-user-name: "bmx-machine"
          git-user-email: "bmx-machine@butterflymx.com"

      - name: Create release
        uses: softprops/action-gh-release@v2
        # https://github.com/softprops/action-gh-release
        with:
          body_path: ./CHANGELOG.md
          tag_name: ${{ steps.bump.outputs.tag }}
