name: bump_version

on:
  workflow_call:
    secrets:
      GITHUB_BUILD_TOKEN:
        required: true

jobs:
  bump_version:
    name: Bump Version
    runs-on: ubuntu-latest

    steps:
    - name: Checkout branch
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.GITHUB_BUILD_TOKEN }}

    - name: Bump version and push tag
      uses: TriPSs/conventional-changelog-action@v3
      with:
        git-message: "chore(release): {version}"
        github-token: ${{ secrets.GITHUB_BUILD_TOKEN }}
        output-file: "app/CHANGELOG.md"
        release-count: 15
        skip-on-empty: "true"
        version-file: "app/functions/package.json"
          