name: bump_node_app_version

on:
  workflow_call:
    secrets:
      GITHUB_BUILD_TOKEN:
        required: true

jobs:
  bump_node_app_version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_BUILD_TOKEN }}

      - name: Bump Version and Tag
        uses: TriPSs/conventional-changelog-action@v3
        with:
          github-token: ${{ secrets.GITHUB_BUILD_TOKEN }}
          release-count: 0
          skip-on-empty: "true"
          version-file: "app/functions/package.json"
