name: deploy_sam_app

on:
  workflow_call:
    inputs:
      node:
        required: false
        type: boolean
      performance:
        required: false
        type: number
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      AWS_REGION:
        required: true

jobs:
  deploy_sam_app:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: app

    steps:
      - name: Checkout Branch
        uses: actions/checkout@v4

      - name: Yarn Install and Build
        if: ${{ inputs.node == true }}
        run: |
          cd functions
          yarn install
          yarn build

      - name: Configure Variables
        id: vars
        env:
          REPOSITORY_NAME: ${{ github.event.repository.name }}
          REF: ${{ github.ref }}
        run: |
          APP_NAME=${REPOSITORY_NAME::-4}
          BRANCH_NAME=$(echo ${REF#refs/heads/} | awk '{ print tolower($0) }')
          echo "::set-output name=app_name::$APP_NAME"
          echo "::set-output name=branch_name::$BRANCH_NAME"
          echo "APP_NAME=$APP_NAME"
          echo "BRANCH_NAME=$BRANCH_NAME"
          echo "GITHUB_RUN_NUMBER=$GITHUB_RUN_NUMBER"

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: SAM Validate
        run: |
          sam validate

      - name: SAM Build
        env:
          # https://github.com/aws/aws-sam-cli/issues/4053#issuecomment-2809486046
          SAM_CLI_BETA_BUILD_PERFORMANCE: ${{ inputs.performance }}
        run: |
          sam build

      - name: SAM Deploy
        env:
          APP_NAME: ${{ steps.vars.outputs.app_name }}
          BRANCH_NAME: ${{ steps.vars.outputs.branch_name }}
          # https://github.com/aws/aws-sam-cli/issues/4053#issuecomment-2809486046
          SAM_CLI_BETA_PACKAGE_PERFORMANCE: ${{ inputs.performance }}
        run: |
          sam deploy \
            --stack-name "$APP_NAME-$BRANCH_NAME" \
            --parameter-overrides "AppName=$APP_NAME BranchName=$BRANCH_NAME" \
            --s3-prefix "$APP_NAME/$BRANCH_NAME/$GITHUB_RUN_NUMBER"
