name: run_linters

on:
  workflow_call:

jobs:
  eslint:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: app/functions

    steps:
      - name: Checkout Branch
        uses: actions/checkout@v2

      - name: Run Linter
        run: yarn lint

  prettier:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: app/functions

    steps:
      - name: Checkout Branch
        uses: actions/checkout@v2

      - name: Run Linter
        run: yarn prettier --check .
